version: "1"

services:
  web:
    type: python

    build:
      command: |
        pip install -r requirements.txt

    run:
      command: |
        python manage.py migrate
        python manage.py collectstatic --noinput
        gunicorn domain_checker.wsgi:application --bind 0.0.0.0:8000

    ports:
      - 8000
