# Generated by Django 4.2.7 on 2026-04-29 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("registered", "Registered (No DNS)"),
                            ("not_found", "Not Found"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_addresses", models.JSONField(default=list)),
                ("registrar", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "registration_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "expiry_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_at"],
            },
        ),
    ]
